# -*- coding: utf-8 -*-
"""Image_to_text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y6sx_Wqz4HxxUbB6COw5ziPHX6ReHAX4
"""


from new.settings import MEDIA_ROOT
from .models import image
import easyocr
import os
def text(x):

    reader=easyocr.Reader(['en'])
    
    
    image3=MEDIA_ROOT+'\\images\\'+x
    result=reader.readtext(image3)

    result

    extracted_test=' '.join([res[1] for res in result])
    
    return(extracted_test)