# Generated by Django 4.0.1 on 2023-08-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
