# Generated by Django 4.0.1 on 2023-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
    ]
